version: '3.8'

services:
  client:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_URL=http://host.docker.internal:5000/api/v1
      - NEXT_PUBLIC_IMAGE_SERVER=https://pub-43a158751ca142c3a51b1b0baa14b50b.r2.dev
    restart: always
