import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/Provider/AuthProvider/AuthProvider";
import ReactQueryClientProvider from "@/Provider/ReactQueryClientProvider";
import Navbar from "@/components/custom/Navbar/Navbar";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ReactQueryClientProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <main>
              <Navbar />
              {children}
            </main>
            <Toaster />
          </body>
        </ReactQueryClientProvider>
      </AuthProvider>
    </html>
  );
}
